// This file is generated by Slice Machine. Update with care!

import Cta from "./Cta";
import Hero from "./Hero";
import TextWithImage from "./TextWithImage";

export { Cta, Hero, TextWithImage };

export const components = {
    cta: Cta,
    hero: Hero,
    text_with_image: TextWithImage,
};
