// This file is generated by Slice Machine. Update with care!

import Cards from "./Cards";
import Cta from "./Cta";
import Hero from "./Hero";
import Tarifs from "./Tarifs";
import TextWithImage from "./TextWithImage";

export { Cards, Cta, Hero, Tarifs, TextWithImage };

export const components = {
    cards: Cards,
    cta: Cta,
    hero: Hero,
    tarifs: Tarifs,
    text_with_image: TextWithImage,
};
